name: Upload Archived Release Assets

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  upload_archived_asset:
    name: Upload Archived Assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create ShokoRelay.bundle
        run: |
            cd ..
            tar -zcvf ShokoRelay.bundle.tar.gz ShokoRelay.bundle/Contents ShokoRelay.bundle/README.md
            zip -r ShokoRelay.bundle.zip ShokoRelay.bundle/Contents ShokoRelay.bundle/README.md
            cd ShokoRelay.bundle
            gh release upload ${{ github.event.release.tag_name }} ../ShokoRelay.bundle.tar.gz
            gh release upload ${{ github.event.release.tag_name }} ../ShokoRelay.bundle.zip
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
